name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cibuild:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use your project's Node.js version
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint
      - name: Run lint
        run: npm run lint
